### ISSUE TITLE
Use proper folder structure for Downloader support

### ISSUE THREAD

**Issue by Jackenmen** [XanderRiga/iracing_cog#19]
This repository currently uses a folder structure that is not supported by Downloader and therefore the cog can't be installed with it.
See the documentation about Publishing cogs for information on how the repository needs to be structured to be usable with Downloader:
https://docs.discord.red/en/stable/guide_publish_cogs.html

**Comment by XanderRiga** [comment]
Thanks for raising this. I have moved away from using red bot so this is no longer applicable. There will be an entirely different way of setting up the bot locally.

**Comment by XanderRiga** [comment]
@jack1142 for what it is worth, the new bot not built into Red is now live(although I am updating very frequently), so there are setup instructions [here](https://github.com/XanderRiga/iracing_bot) if you want the newer code
