### ISSUE TITLE
!!FIX!!! Could not connect to any X display. | wkhtmltoimage wont work

### ISSUE THREAD

**Issue by velotoxicsounds** [XanderRiga/iracing_cog#21]
On my Ubuntu 18.04 LTS server the Iracing COG bot could not be used correctly. I have now fixed this error.

[P] = your Chat Prefix

1. Start Bot, say "[P]pipinstall imgkit" and "[P]pipinstall pyvirtualdisplay"
2. Log in to your server with SSH, run "sudo apt-get install wkhtmltopdf" command
3. Then run the command "sudo apt-get install xvfb" via SSH.
4. Restart your server, log in to your server via FTP and open the file "all_series.py" in the path "iracing_cog/commands"

Mark everything , delete the content and insert this code.

#########################################################

from ..html_builder import *
from ..helpers import cleanup_file
import imgkit
from pyvirtualdisplay import Display

class AllSeries:
    def __init__(self, log):
        self.log = log

    async def call(self, ctx, all_series):
        road, oval, dirt_road, dirt_oval = [], [], [], []
        for season in all_series:
            if season.cat_id == 2:
                road.append(season)
            if season.cat_id == 1:
                oval.append(season)
            if season.cat_id == 4:
                dirt_road.append(season)
            if season.cat_id == 3:
                dirt_oval.append(season)

        html_strings = [
            build_series_html_string(road, 'Road Series'),
            build_series_html_string(oval, 'Oval Series'),
            build_series_html_string(dirt_road, 'Dirt Road Series'),
            build_series_html_string(dirt_oval, 'Dirt Oval Series')
        ]

        for string in html_strings:
            display = Display(visible=0, size=(600,600))
            display.start()
            filename = f'{ctx.guild.id}_series.jpg'
            imgkit.from_string(string, filename)
            await ctx.send(file=discord.File(filename))
            cleanup_file(filename)
            display.stop()

**Comment by XanderRiga** [comment]
wkhtmltopdf does require some setup, but `pyvirtualdisplay` is not needed here. You can follow the instructions to install the binary for your platform as detailed here: https://pypi.org/project/imgkit/ in step 2
