### ISSUE TITLE
FIX | Pyracing Login Client

### ISSUE THREAD

**Issue by velotoxicsounds** [XanderRiga/iracing_cog#22]
Change in iracing.py

Orginal:
from pyracing import client as pyracing
New:
from pyracing.client import Client

Orginal:
        self.pyracing = pyracing.Client(
            os.getenv("IRACING_USERNAME"),
            os.getenv("IRACING_PASSWORD")
        )
NEW:
self.pyracing = Client(username, password)

Orginal:
logdna_key = os.getenv("LOGDNA_INGESTION_KEY")
log = logging.getLogger('logdna')
log.setLevel(logging.DEBUG)
handler = LogDNAHandler(logdna_key, {'hostname': os.getenv("LOG_LOCATION")})
log.addHandler(handler)
New:
logdna_key = os.getenv("LOGDNA_INGESTION_KEY")
log = logging.getLogger('logdna')
log.setLevel(logging.DEBUG)
handler = LogDNAHandler(logdna_key, {'hostname': os.getenv("LOG_LOCATION")})
log.addHandler(handler)
username = 'IRACINGACCOUNTUSERNAME'
password = 'IRACINGPASSWORD'

**Comment by XanderRiga** [comment]
Thanks for this, but I am explicitly using `python-dotenv` to load in these values. I may change it in the future to take values in from the parent bot that runs this, but for now I want the cog to be standalone. You will need to create a file in the root of the cog called `.env` that contains `IRACING_USERNAME=your username` and `IRACING_PASSWORD=your password` to get those values.
